### ISSUE TITLE
CICD_003-도커파일 생성 후 빌드 시 이미지 생성 자동화

### ISSUE THREAD

**Issue by jiieunn2** [beyond-sw-camp/be02-fin-Hello_R_loha-HRsystem#158]
빌드 시 , 도커 파일 생성되도록 만들도록 설정한다.

도커 파일로 만든 이미지가 정상작동하는지 확인한다.
프론트엔드 이미지 파일 작성
백엔드 이미지 파일 작성

**Comment by LCH-97** [comment]
참고1

https://velog.io/@passion_hd/Devops-2-GitHub-Action-Selenium

**Comment by Lee-Jun-Guk** [comment]
참고2

https://velog.io/@passion_hd/Docker-2%EC%9D%BC%EC%B0%A8-%EC%8B%A4%EC%8A%B5-%EC%A0%95%EB%A6%AC
