### ISSUE TITLE
CICD_007-파이프 라인 코드

### ISSUE THREAD

**Issue by LCH-97** [beyond-sw-camp/be02-fin-Hello_R_loha-HRsystem#159]
cicd에 필요한 파이프 라인 코드를 작성한다.

산출물
백엔드 파이프라인 코드
프론트엔드 파이프라인  코드
파이프 라인 작동되는 화면

**Comment by thanks9807** [comment]
결과물 예시
https://github.com/beyond-sw-camp/be02-4th-developer_passion-fashion/blob/main/jenkins/backend/jenkinsfile
