### ISSUE TITLE
CICD_004-테스트 코드 작성

### ISSUE THREAD

**Issue by jiieunn2** [beyond-sw-camp/be02-fin-Hello_R_loha-HRsystem#160]
테스트 코드 작성하도록 한다.

프론트엔드 테스트코드 작성하도록 한다.
백엔드 테스트코드 작성하도록 한다.

**Comment by LCH-97** [comment]
백엔드 테스트코드

[bbb.zip](https://github.com/beyond-sw-camp/be02-fin-Hello_R_loha-HRsystem/files/14626007/bbb.zip)

**Comment by jiieunn2** [comment]
프론트엔드 테스트코드

https://velog.io/@passion_hd/Devops-2-GitHub-Action-Selenium

**Comment by LCH-97** [comment]
프론트엔드 테스트코드

[frontend.zip](https://github.com/beyond-sw-camp/be02-fin-Hello_R_loha-HRsystem/files/14626008/frontend.zip)

**Comment by thanks9807** [comment]
- 백엔드 직원 생성, 부서 생성, 포지션 생성에 대한 테스트 코드 작성
- 깃허브 액션을 이용한 mvn test 자동화 코드 생성

**Comment by thanks9807** [comment]
- 백엔드 직원 생성, 부서 생성, 포지션 생성에 대한 테스트 코드 작성
- 깃허브 액션을 이용한 mvn test 자동화 코드 생성

**Comment by thanks9807** [comment]
- 백엔드 직원 생성, 부서 생성, 포지션 생성에 대한 테스트 코드 작성
- 깃허브 액션을 이용한 mvn test 자동화 코드 생성

**Comment by thanks9807** [comment]
- 백엔드 직원 생성, 부서 생성, 포지션 생성에 대한 테스트 코드 작성
- 깃허브 액션을 이용한 mvn test 자동화 코드 생성
