### ISSUE TITLE
DATA_001- 출퇴근 데이터 생성

### ISSUE THREAD

**Issue by kkm4232** [beyond-sw-camp/be02-fin-Hello_R_loha-HRsystem#245]
출근시간, 퇴근시간을 알 수 있다

**Comment by kkm4232** [comment]
[출근데이터.xlsx](https://github.com/beyond-sw-camp/be02-fin-Hello_R_loha-HRsystem/files/14785313/default.xlsx)
[초과근무데이터.xlsx](https://github.com/beyond-sw-camp/be02-fin-Hello_R_loha-HRsystem/files/14785316/default.xlsx)

**Comment by LCH-97** [comment]
[출근데이터 완성.csv](https://github.com/beyond-sw-camp/be02-fin-Hello_R_loha-HRsystem/files/14833963/default.csv)
