### ISSUE TITLE
CICD 계획서 작성

### ISSUE THREAD

**Issue by thanks9807** [beyond-sw-camp/be02-fin-Hello_R_loha-HRsystem#330]
CICD 계획서 작성

CI/CD 아키텍처
CI/CD 기술 스택
프론트 엔드 CI 과정
프론트 엔드 CD 과정
백 엔드 CI 과정
백 엔드 CD 과정

사진 첨부 및 설명 추가

**Comment by dhkdtld37** [comment]
안녕하세요 레포 구경하다가 실수로 프로젝트 칸반에서 해당 이슈 위치 이동으로 기록이 남게 되어 코멘트 남깁니다. 죄송합니다.
